// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: image_classification.proto

package image_classifier

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClassifyImageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Contains a list of classification identifier results.
	Matches []float32 `protobuf:"fixed32,1,rep,packed,name=matches,proto3" json:"matches,omitempty"`
	// Contains serialized ndarray of the classified image outlined with the match.
	Image []byte `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	// Device IP/name which captured the image.
	Device string `protobuf:"bytes,3,opt,name=device,proto3" json:"device,omitempty"`
}

func (x *ClassifyImageResponse) Reset() {
	*x = ClassifyImageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_image_classification_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClassifyImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassifyImageResponse) ProtoMessage() {}

func (x *ClassifyImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_image_classification_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassifyImageResponse.ProtoReflect.Descriptor instead.
func (*ClassifyImageResponse) Descriptor() ([]byte, []int) {
	return file_image_classification_proto_rawDescGZIP(), []int{0}
}

func (x *ClassifyImageResponse) GetMatches() []float32 {
	if x != nil {
		return x.Matches
	}
	return nil
}

func (x *ClassifyImageResponse) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *ClassifyImageResponse) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

type ClassifyImageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Contains serialized ndarray of the image to classify.
	Image []byte `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	// Device IP/name which captured the image.
	Device string `protobuf:"bytes,2,opt,name=device,proto3" json:"device,omitempty"`
}

func (x *ClassifyImageRequest) Reset() {
	*x = ClassifyImageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_image_classification_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClassifyImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassifyImageRequest) ProtoMessage() {}

func (x *ClassifyImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_image_classification_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassifyImageRequest.ProtoReflect.Descriptor instead.
func (*ClassifyImageRequest) Descriptor() ([]byte, []int) {
	return file_image_classification_proto_rawDescGZIP(), []int{1}
}

func (x *ClassifyImageRequest) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *ClassifyImageRequest) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

var File_image_classification_proto protoreflect.FileDescriptor

var file_image_classification_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x43, 0x6c,
	0x61, 0x73, 0x73, 0x69, 0x66, 0x69, 0x65, 0x72, 0x22, 0x5f, 0x0a, 0x15, 0x43, 0x6c, 0x61, 0x73,
	0x73, 0x69, 0x66, 0x79, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x02, 0x52, 0x07, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x22, 0x44, 0x0a, 0x14, 0x43, 0x6c, 0x61,
	0x73, 0x73, 0x69, 0x66, 0x79, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x32,
	0x6b, 0x0a, 0x0f, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x69,
	0x65, 0x72, 0x12, 0x58, 0x0a, 0x0d, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x79, 0x49, 0x6d,
	0x61, 0x67, 0x65, 0x12, 0x20, 0x2e, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x69, 0x65, 0x72,
	0x2e, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x79, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x69,
	0x65, 0x72, 0x2e, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x79, 0x49, 0x6d, 0x61, 0x67, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x30, 0x01, 0x42, 0x18, 0x5a, 0x16,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x63, 0x6c, 0x61, 0x73,
	0x73, 0x69, 0x66, 0x69, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_image_classification_proto_rawDescOnce sync.Once
	file_image_classification_proto_rawDescData = file_image_classification_proto_rawDesc
)

func file_image_classification_proto_rawDescGZIP() []byte {
	file_image_classification_proto_rawDescOnce.Do(func() {
		file_image_classification_proto_rawDescData = protoimpl.X.CompressGZIP(file_image_classification_proto_rawDescData)
	})
	return file_image_classification_proto_rawDescData
}

var file_image_classification_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_image_classification_proto_goTypes = []interface{}{
	(*ClassifyImageResponse)(nil), // 0: Classifier.ClassifyImageResponse
	(*ClassifyImageRequest)(nil),  // 1: Classifier.ClassifyImageRequest
}
var file_image_classification_proto_depIdxs = []int32{
	1, // 0: Classifier.ImageClassifier.ClassifyImage:input_type -> Classifier.ClassifyImageRequest
	0, // 1: Classifier.ImageClassifier.ClassifyImage:output_type -> Classifier.ClassifyImageResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_image_classification_proto_init() }
func file_image_classification_proto_init() {
	if File_image_classification_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_image_classification_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClassifyImageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_image_classification_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClassifyImageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_image_classification_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_image_classification_proto_goTypes,
		DependencyIndexes: file_image_classification_proto_depIdxs,
		MessageInfos:      file_image_classification_proto_msgTypes,
	}.Build()
	File_image_classification_proto = out.File
	file_image_classification_proto_rawDesc = nil
	file_image_classification_proto_goTypes = nil
	file_image_classification_proto_depIdxs = nil
}
